name: Publish to Packagist

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'Force publish to Packagist'
        required: false
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to Packagist
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: json, curl
        
    - name: Validate composer.json
      run: composer validate --strict
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader
      
    - name: Run tests
      run: |
        composer install --prefer-dist --no-progress
        vendor/bin/phpunit
        
    - name: Create release archive
      run: |
        mkdir -p dist
        rsync -av --progress \
          --exclude='dist' \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='tests' \
          --exclude='phpunit.xml' \
          --exclude='phpcs.xml' \
          --exclude='phpstan.neon' \
          --exclude='.gitignore' \
          --exclude='setup.php' \
          --exclude='CONTRIBUTING.md' \
          --exclude='.env.example' \
          . dist/
          
    - name: Update Packagist
      run: |
        if [ "${{ github.event_name }}" = "release" ] || [ "${{ github.event.inputs.force_publish }}" = "true" ]; then
          curl -XPOST -H'content-type:application/json' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
            -d'{"repository":{"url":"https://github.com/sdkwa/whatsapp-api-client-php"}}'
        fi